sudo: requared
dist: trusty

language: 
    - cpp

compiler: 
    - gcc


before_install:
    - git submodule update --recursive --init 
    - chmod +x install-cocos2d-x.sh
    - ./install-cocos2d-x.sh

script:
    - cocos compile -p linux -s . 

