sudo: requared
dist: trusty

language: 
    - cpp

compiler: 
    - gcc


install:
    - git submodule update --recursive --init 
    - chmod +x install-cocos2d-x.sh
    - source ./install-cocos2d-x.sh
    - echo $PATH
    - ls -l $HOME/cocos/cocos2d-x-3.15.1/tools/cocos2d-console/bin/cocos 
    - chmod +x $HOME/cocos/cocos2d-x-3.15.1/tools/cocos2d-console/bin/cocos

script:
    - echo $PATH
    - cocos compile -p linux -s .

